# Generated by Django 5.2.8 on 2025-11-16 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(help_text='Building/Floor/Section', max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('access_code', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lockers',
                'ordering': ['locker_number'],
            },
        ),
        migrations.CreateModel(
            name='LockerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small (12" x 12" x 18")'), ('medium', 'Medium (18" x 18" x 24")'), ('large', 'Large (24" x 24" x 36")'), ('xlarge', 'Extra Large (36" x 36" x 48")'), ('climate', 'Climate Controlled')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_climate_control', models.BooleanField(default=False)),
                ('has_security_monitoring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locker_types',
                'ordering': ['size', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LockerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('duration_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('duration_count', models.IntegerField(default=1, help_text='Number of hours/days/weeks/months')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('access_code', models.CharField(max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('items_description', models.TextField(blank=True, help_text='Description of items stored')),
                ('notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lockers.locker')),
            ],
            options={
                'db_table': 'locker_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LockerAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Opened'), ('close', 'Closed'), ('access_denied', 'Access Denied'), ('maintenance', 'Maintenance Access')], max_length=20)),
                ('access_code_used', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='lockers.locker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lockers.lockerbooking')),
            ],
            options={
                'db_table': 'locker_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='locker',
            name='locker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='lockers.lockertype'),
        ),
    ]
