# Generated by Django 4.2.7 on 2025-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locker_images/'),
        ),
    ]
