# Generated by Django 4.2.7 on 2025-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_locker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockerbooking',
            name='liability_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lockerbooking',
            name='penalty_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lockerbooking',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
