# Generated by Django 4.2.7 on 2025-12-12 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lockers', '0003_lockerbooking_liability_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lockers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locker',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lockers', to=settings.AUTH_USER_MODEL),
        ),
    ]
