# Generated by Django 5.2.8 on 2025-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_idx_order_number_order_idx_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='openid',
            field=models.CharField(default='', help_text='Store/User Identifier', max_length=255, verbose_name='OpenID'),
        ),
    ]
