# Generated by Django 4.2.7 on 2025-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentalitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='duration_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='duration_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='liability_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='penalty_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
