# Generated by Django 4.2.7 on 2025-12-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product'), ('storage', 'Storage Unit'), ('locker', 'Locker Type'), ('marketplace', 'Marketplace'), ('rental', 'Rental Equipment'), ('expense', 'Expense')], max_length=20),
        ),
    ]
