# Generated by Django 5.2.8 on 2025-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=255, unique=True, verbose_name='Goods Code')),
                ('goods_desc', models.CharField(max_length=255, verbose_name='Goods Description')),
                ('goods_supplier', models.CharField(max_length=255, verbose_name='Goods Supplier')),
                ('goods_weight', models.FloatField(default=0, verbose_name='Goods Weight')),
                ('goods_w', models.FloatField(default=0, verbose_name='Goods Width')),
                ('goods_d', models.FloatField(default=0, verbose_name='Goods Depth')),
                ('goods_h', models.FloatField(default=0, verbose_name='Goods Height')),
                ('goods_unit', models.CharField(max_length=255, verbose_name='Goods Unit')),
                ('goods_class', models.CharField(max_length=255, verbose_name='Goods Class')),
                ('goods_brand', models.CharField(max_length=255, verbose_name='Goods Brand')),
                ('safety_stock', models.BigIntegerField(default=0, verbose_name='Safety Stock')),
                ('goods_cost', models.FloatField(default=0, verbose_name='Goods Cost')),
                ('goods_price', models.FloatField(default=0, verbose_name='Goods Price')),
                ('bar_code', models.CharField(blank=True, max_length=255, verbose_name='Bar Code')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'db_table': 'goods',
                'ordering': ['-id'],
            },
        ),
    ]
