# Generated by Django 5.2.8 on 2025-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='min_stock_level',
            field=models.IntegerField(default=10, verbose_name='Minimum Stock Level'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='reorder_point',
            field=models.IntegerField(default=5, verbose_name='Reorder Point'),
        ),
    ]
