# Generated by Django 5.2.8 on 2025-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_listmodel_expiry_date_listmodel_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['goods_code'], name='idx_goods_code'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['goods_class'], name='idx_goods_class'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['goods_brand'], name='idx_goods_brand'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['bar_code'], name='idx_bar_code'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['create_time'], name='idx_goods_created'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['goods_code', 'is_delete'], name='idx_goods_active'),
        ),
    ]
