# Generated by Django 5.2.8 on 2025-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_listmodel_idx_goods_code_listmodel_idx_goods_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='openid',
            field=models.CharField(default='', help_text='User/Store Identifier', max_length=255, verbose_name='OpenID'),
        ),
    ]
