# Generated by Django 4.2.7 on 2025-12-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
        ('storage', '0002_storageunit_created_by'),
        ('rentals', '0002_rentalitem_created_by'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='duration_count',
            field=models.IntegerField(default=1, help_text='Number of duration units'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='duration_type',
            field=models.CharField(blank=True, help_text='hourly, daily, weekly, monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Marketplace Product'), ('rental', 'Rental Item'), ('storage', 'Storage Unit'), ('locker', 'Locker')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lockers.locker'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rental_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.rentalitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='storage_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storageunit'),
        ),
    ]
