# Generated by Django 5.2.8 on 2025-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=255, verbose_name='Goods Code')),
                ('goods_desc', models.CharField(max_length=255, verbose_name='Goods Description')),
                ('goods_qty', models.BigIntegerField(default=0, verbose_name='Total Qty')),
                ('onhand_stock', models.BigIntegerField(default=0, verbose_name='On Hand Stock')),
                ('can_order_stock', models.BigIntegerField(default=0, verbose_name='Available Stock')),
                ('ordered_stock', models.BigIntegerField(default=0, verbose_name='Ordered Stock')),
                ('damage_stock', models.BigIntegerField(default=0, verbose_name='Damage Stock')),
                ('supplier', models.CharField(default='', max_length=255, verbose_name='Supplier')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'stocklist',
                'ordering': ['-id'],
            },
        ),
    ]
