# Generated by Django 5.2.8 on 2025-11-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockalert_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklistmodel',
            name='goods_image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_images/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='openid',
            field=models.CharField(default='', max_length=255, verbose_name='User'),
        ),
    ]
