# Generated by Django 5.2.8 on 2025-11-22 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stocklistmodel_goods_image_stocklistmodel_openid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['goods_code'], name='idx_alert_goods'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['is_resolved'], name='idx_alert_resolved'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_level', 'is_resolved'], name='idx_alert_active'),
        ),
        migrations.AddIndex(
            model_name='stocklistmodel',
            index=models.Index(fields=['goods_code'], name='idx_stock_goods'),
        ),
        migrations.AddIndex(
            model_name='stocklistmodel',
            index=models.Index(fields=['goods_code', 'openid'], name='idx_stock_user'),
        ),
        migrations.AddIndex(
            model_name='stocklistmodel',
            index=models.Index(fields=['create_time'], name='idx_stock_created'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['goods_code'], name='idx_movement_goods'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='idx_movement_type'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='idx_movement_created'),
        ),
    ]
