# Generated by Django 4.2.7 on 2025-12-03 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_purchase',
            new_name='min_amount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='max_uses',
            new_name='usage_count',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_to',
            new_name='valid_until',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_count',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Services'), ('rentals', 'Rentals'), ('storage', 'Storage Units'), ('lockers', 'Lockers'), ('marketplace', 'Marketplace'), ('pos', 'POS')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(blank=True, help_text='Total usage limit', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='coupon',
            table=None,
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
