# Generated by Django 5.2.8 on 2025-11-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='warehouse_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Warehouse Image'),
        ),
    ]
