# Generated by Django 4.2.7 on 2025-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_listmodel_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='can_list_rentals',
            field=models.BooleanField(default=True, verbose_name='Can list rental items'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='can_list_storage',
            field=models.BooleanField(default=True, verbose_name='Can list storage units'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='is_marketplace_seller',
            field=models.BooleanField(default=True, verbose_name='Can sell in marketplace'),
        ),
    ]
