# Generated by Django 5.2.8 on 2025-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['customer_name'], name='idx_customer_name'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['customer_city'], name='idx_customer_city'),
        ),
        migrations.AddIndex(
            model_name='listmodel',
            index=models.Index(fields=['create_time'], name='idx_customer_created'),
        ),
    ]
