# Generated by Django 5.2.8 on 2025-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_listmodel_idx_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='openid',
            field=models.CharField(default='', help_text='Store Identifier', max_length=255, verbose_name='OpenID'),
        ),
    ]
