# Generated by Django 5.2.8 on 2025-11-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin (Partner)'), ('subadmin', 'SubAdmin (Manager)'), ('supervisor', 'Supervisor (SeniorStaff)'), ('staff', 'Staff (Employee)'), ('customer', 'Customer'), ('customer_seller', 'Customer Seller'), ('guest', 'Guest')], default='customer', max_length=20),
        ),
    ]
