# Generated by Django 4.2.7 on 2025-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_remove_customer_seller_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin (Partner)'), ('subadmin', 'SubAdmin (Supervisor)'), ('staff', 'Staff (Employee)'), ('customer', 'Customer'), ('guest', 'Guest')], default='customer', max_length=20),
        ),
    ]
