# Generated by Django 4.2.7 on 2025-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storageunit_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage_images/'),
        ),
    ]
