# Generated by Django 4.2.7 on 2025-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storageunit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='liability_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='penalty_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
