# Generated by Django 4.2.7 on 2025-12-12 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0004_storagebooking_liability_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_storage_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
